### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by godreborn** [C3RV1/UndertaleNDS#1]
I have a problem when compiling, and it's related to not finding nitrofs.  I know it should be in the main undertale folder, but I have no idea what it's talking about.  I found nothing substantial from a google search either.

**Comment by C3RV1** [comment]
All game files (audio, sprites, background...) are copyrighted by Toby Fox, so they cannot be included in plain text. The missing folder, named nitrofs, contains all this data, so I cannot include it directly.

What I will do is provide a file named nitrofs.zip.aes and a utility named decode.py, so that you can decode the aes file using the game's original data.win file as the key. This way I'll make sure you in fact own the original game. These .aes files will be included in the releases. If you really wish to play the game in its current state, I could create a release.
