### ISSUE TITLE
Reproducing the .aes files found in the Releases tab

### ISSUE THREAD

**Issue by CerisWhite** [C3RV1/UndertaleNDS#3]
Could I get a quick write-up of how this is done? I haven't personally touched NDS homebrew before and there doesn't seem to be any indication in the readme of how this set of files was created in the first place.

Thank you kindly!

**Comment by C3RV1** [comment]
Hi!

The instructions on how to decode the .aes files are on the 'Installation' part of the README. Basically, to decrypt the files containing copyrighted material you need access to the original game files. Then, you have to copy the "data.win" from the original game files to the root directory of the project and run the "decrypt_all.sh" script.

Did this solve any doubts? Or were you asking about how the .aes files are created on the first place?

Cervi

**Comment by CerisWhite** [comment]
I was asking how you created them. Specifically the tools and nitrofs aes encrypted files.

**Comment by C3RV1** [comment]
You must first download tools.zip.aes and nitrofs.zip.aes. Then run ./decrypt_all.sh which should decrypt the aes files to the corresponding folders.

Nitrofs and tools are not extracted from the original game but hand-crafted, thus they can't be exported from the original game. You must decode the .aes files to be able to compile the game.

**Comment by CerisWhite** [comment]
Alright then, that would mean my question is how I can create the nitrofs and tool archives myself. I imagine it's because of Windows/Cygwin, but I cannot decrypt these files properly. I get no error about my data.win hash not matching, but the resulting decrypted .zip file isn't a proper zip file, according to python.

**Comment by C3RV1** [comment]
could you maybe share the console output from running decrypt_all.sh

**Comment by jonbarrow** [comment]
If those files are hand-crafted, and are put up for download on the releases page, _and_ are required for building, what exactly is the purpose of distributing them this way?

Is there some kind of advantage or limitation I'm not aware of that requires these to be downloaded manually as encrypted files, only to then be immediately decrypted?

Why not just include them in the original source if they are hand-crafted? I take that to mean they do not contain any copyrighted material, so I don't see any reason to not include them in the source?

**Comment by C3RV1** [comment]
@jonbarrow by hand-crafted I mean that they cannot be automatically extracted from data.win. What I do is take them from the original game and slightly adapt them for the Nintendo DS (manually, can't be done by a script). They do contain copyrighted material I cannot share without verify you already own the original data. That's why they are uploaded encrypted.

**Comment by jonbarrow** [comment]
If it contains copyrighted data you can't distribute it _at all_. It doesn't mean you just "check if they own the original game". You don't have the legal rights to distribute any copyrighted material like that, even if it is encrypted or modified

If that's what's happening here then despite what your README says, this repo absolutely facilitates piracy

I would highly suggest changing tactics. Even if that means having a bunch of highly-specific scripts doing all these changes on user provided dumps

**Comment by C3RV1** [comment]
Well more than distributing the copyrighted material it distributes a file which modifies the original game bytes to generate the corresponding project files. You can consider the .aes files as patch files to the original game bytes.

**Comment by CerisWhite** [comment]
Several of the files in your repository indicate that it's not so simple as a patch. It's clear you're cutting down sprites/backgrounds and converting them to your own unique format.

I'm not asking you to change your distribution model or what have you, though the piracy is a valid concern; I just want an explanation of the files in your nitrofs.zip. Even a simple write-up of the steps you took to modify the sprites before converting them is enough. It's impossible to contribute in any way when the repository is incomplete and there's no explanations on how the most important aspect of the project works.

More importantly, why go through the trouble of creating a new file format when bmp and png are already perfectly usable for NDS homebrew?

**Comment by jonbarrow** [comment]
> Well more than distributing the copyrighted material it distributes a file which modifies the original game bytes to generate the corresponding project files. You can consider the .aes files as patch files to the original game bytes.

This is misleading/disingenuous at best, and a straight up lie at worst? I just decrypted the files from the latest release and you can _clearly_ see the original assets in them

Even if you modified the original assets, your claim that you are just distributing patches is misleading. You make it sound like these are IPS-style patches, where only the data which has been changed is distributed. That is not the case here, all you are doing is encoding the modified original assets, in full, into your own proprietary file formats

That is a clear violation of copyright. Your original statement was correct, these encrypted files contain copyrighted content which you have no rights to distribute

The fact that you have gone out of your way to hide these assets by not only encrypting the originals, but also converting them into your own proprietary file formats, is very shady

I would highly suggest moving away from this type of distribution

**Comment by tilderain** [comment]
Chill out dude, while I'd definitely like to see a better implementation andor scripting of those files into this repo,
there's no reason to rag on this poor soul for allegedly concocting some evil scheme to commit copyright infringement, hide it, and inspire everyone to pirate undertale by... getting the original game's files and downloading the repo's files in order to....?????. in an ideal world, toby fox would get all the fangame creators arrested for distributing copyrighted content, but since we're not in that world, i think this is just ok

**Comment by C3RV1** [comment]
It seems you've misunderstood my intentions and the reason why I'm using proprietary file formats. I'll publish a thorough response to each of the aspects you've mentioned today, but right now I don't have enough time to explain everything. I'm posting this message so that you know I'm not ignoring you or anything like that.

**Comment by C3RV1** [comment]
Okay, I'll address all your concerns point by point. I'll address them in the following order: the use of proprietary file formats, the distribution of the project and contributing to the project. But first I'll give some background information on the project just to contextualize everything. I recommend you read everything in order  to fully understand my intentions. I'm answering all your questions @jonbarrow @CerisWhite @tilderain .

## Background
I'm a 16 year old currently undergoing high school. The reason I'm mentioning this is that this project is the practical part of a research project I have to turn in by December. My aim for the project was to work as closely with the video hardware as possible, therefore getting an in-depth knowledge of how the Nintendo DS worked internally.

What this meant is that I wanted to only use `libnds` and no other external libraries for this project, which is what drove me to creating the proprietary file formats.

## Proprietary file formats

The reason why I created this files formats even when `png` and `bmp` already exist is that I had neither the time nor the dedication to understand and fully implement those file formats. I comprehend that the file size of a `png` file is way lower than its `cbgf` counterpart. The reason for this difference is that `png` utilizes a really good compression algorithm, which is also rather complex. Therefore, I opted to create these file formats suited specifically for my needs.

If you want to understand how these file formats work I recommend you look at the `include/Formats` directory, which contains a kind of "reference" for each file format, as well as the `tools` directory. There is a `pngToCbgf.py` script in there. There is a handful of scripts which convert usual formats to my formats.

## Distribution of the project

I want to make clear from the get-go that I don't promote piracy nor want anyone to indulge in it. The project files have been severely modified using Aseprite from the originals, so modification by script is not an option, or is not feasible for now.

Because of what I've mentioned before, I needed another system to distribute the files. From my understanding, which might be incorrect, a patch is a function which works in more or less the following way:

You take the original file (`data.win`), you run it through a patch function taking a "patch file" (`.aes files`, which by themselves do only include gibberish) and transforms the bytes into a usable format (`tools`/`nitrofs`). The `.aes` files therefore do not include any copyrighted material without supplying the original game data too. They just contain "instructions" on how to alter the original bytes in combination with the `.aes` file to produce the copyrighted material, already owned by the used if they are in possession of `data.win`.

## Contributing to the project
As I mentioned at the start of the Background section, this project is due by December, so I've rushed all the code for now, what means that I've not documented any of it and haven't considered maintainability for now. Once I've turned in my high-school project and I continue with it as a personal project, maybe I could get the documentation down as well as figure a way in which you could contribute to the project.

Also, as my project has to be 100% mine, I can't turn in work done by other people, so contributions are not allowed (for now, sorry :/). Still, if you wish to modify the game in any way, you can add files, sprites, rooms and cutscenes to the `tools` directory and use `tools/all.py` to compile them into the corresponding nitrofs files.

## Conclusion
I hope I've successfully explained the situation. As you can see, I don't intend to promote any type of piracy. The proprietary file formats are not "an effort to hide" any assets. Of course they increase size, but they also facilitate and simplify the code decoding them.

I can't create scripts automatically modifying the original data for now. I can't change the file formats right now. I hope you understand I'm severely limited by time. The only alternative right now would be to delete the uploaded `.aes` files from the releases, which would make it inaccessible to anyone. Only the gameplay videos on Youtube would allow anyone to see the project.

This is quite a serious post, not my style, forgive me for any mistakes :)
Any suggestions are appreciated, although I may or may not follow them.
